version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: provider-ms
    ports:
      - "8085:9091"
    depends_on:
      - database
  database:
    image: postgres:latest
    container_name: provider-ms
    environment:
      - POSTGRES_PASSWORD="password"
      - POSTGRES_USER="user"
      - POSTGRES_DB="tech-talk-db"
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: